[workspace]
changelog_update = true
git_release_enable = true
features_always_increment_minor = false

[[package]]
name = "agenterra"
release = true
publish = false

[[package]]
name = "agenterra-core"
release = true
publish = false
